language: python
python: 3.7
addons:
  apt:
    update: true
    packages:
    - xvfb
services:
- xvfb
cache:
  apt: true
  ccache: true
  directories:
  - "$HOME/.cache"
env:
  global:
  - secure: EkWLZhbrp/mXJOx38CHjs7BnjXafsqHtwxPQrqWy457VDFWhIY1DMnIR/lOWG+a20Qv52sCsFtiZEmMfUjf0pLGXOqurdxbYBGJ7/ikFLk9yV2rDwiArUlVM9bWFnFxHvdz9zewBH55WurrY4ShZWyV+x2dWjjceWG5VpWeI6sA=
git:
  depth: false
matrix:
  fast_finish: true
  include:
  - arch: arm64
    env:
    - JOB="3.7, arm64" PYTEST_WORKERS=1 ENV_FILE="ci/deps/travis-37-arm64.yaml" PATTERN="(not
      slow and not network and not clipboard and not arm_slow)"
before_install:
- openssl aes-256-cbc -K $encrypted_2a68b6131c57_key -iv $encrypted_2a68b6131c57_iv
  -in root_key.enc -out root_key -d
- echo "before_install"
- python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL);
  fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
- source ci/travis_process_gbq_encryption.sh
- export PATH="$HOME/miniconda3/bin:$PATH"
- df -h
- pwd
- uname -a
- git --version
- "./ci/check_git_tags.sh"
install:
- echo "install start"
- ci/prep_cython_cache.sh
- ci/setup_env.sh
- ci/submit_cython_cache.sh
- echo "install done"
before_script:
- travis_wait 30 bash test_mypy.sh
